version: 1.0.{build}
#clone_script:
#- ps: 'write-host "cloning... this replaces default clone method"'

install:
- set PATH=C:\Ruby25-x64\bin;%PATH%
- git submodule update --init --recursive
- ps: scripts/lib/init.ps1 .
- ps: scripts/init.ps1 .
- ps: scripts/lib/restore.ps1 .
- ps: scripts/restore.ps1

#assembly_info:
#  patch: true
#  file: '**\AssemblyInfo.*'
#  assembly_version: '{version}'
#  assembly_file_version: '{version}'
#  assembly_informational_version: '{version}'

build_script:
- ps: write-host "no need to build powershell"
test_script:
- ps: scripts/test.appveyor.ps1

on_success:
- ps: 'write-host "event: build success!"'
on_failure:
- ps: 'write-host "event: build error!"'
on_finish:
- ps: 'write-host "event: build finish!"'

# TODO: only push modules that changed
deploy_script:
- ps: $branch = $env:APPVEYOR_REPO_BRANCH; write-host "Branch=$branch"
- ps: >-
    $branch = $env:APPVEYOR_REPO_BRANCH;
    $autodeploy = $false;
    if ($autodeploy) {
        if ($branch -eq "master") { 
            scripts/lib/push.ps1 . -buildno $env:APPVEYOR_BUILD_NUMBER; 
        } else { 
            write-warning "not deploying from branch $branch";
        }
    } else {
        write-warning "autodeploy disabled";
    }


artifacts:
- path: artifacts
